# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db93e612e50e5a486ff7c304ab553f20e2018c548f57746b26617cfc0b5d7ffe36a77a247ceb38a86abdb35a03fb487331941cbb999a84539134395e99f2440

test:
  secret_key_base: d4cf525dff75210e6f721527f83d21d7ae58a8746803ba65c731e8da19089f277e69eb87ae873796aa96572ec56bfb79a3d9642d7cc6bcf4880193e9f5eb49c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
